name: afghan_cosmos
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.7
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  flutter_riverpod: ^2.5.1
  uuid: ^4.3.3
  path_provider: ^2.1.5
  mime: ^2.0.0
  iconsax: ^0.0.8
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  html: ^0.15.6
  http: ^1.4.0
  logger: ^2.5.0
  google_fonts: ^6.2.1  
  animated_text_kit: ^4.2.3
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - .env

