// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5cRbN3gqskwj3EohZmcnfpM657zgQHm8',
    appId: '1:736443589610:web:cf67be4a7cff815a4a8893',
    messagingSenderId: '736443589610',
    projectId: 'afghancosmos-efbfc',
    authDomain: 'afghancosmos-efbfc.firebaseapp.com',
    storageBucket: 'afghancosmos-efbfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkBzhAWLWoRoHq-yxJhh4-VjsAJh35F8',
    appId: '1:736443589610:android:185817c9c21b78994a8893',
    messagingSenderId: '736443589610',
    projectId: 'afghancosmos-efbfc',
    storageBucket: 'afghancosmos-efbfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRFQu7SEOLHlFodCJu5_-u-v3aEm1P4g',
    appId: '1:736443589610:ios:5fed159eb0be09654a8893',
    messagingSenderId: '736443589610',
    projectId: 'afghancosmos-efbfc',
    storageBucket: 'afghancosmos-efbfc.firebasestorage.app',
    iosBundleId: 'com.example.afghanCosmos',
  );
}
